---
title: "Data Engineering_presentation_SJ KIM"
author: "SeongJin Kim"
date: "2019년 10월 25일"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### **MBTI 성격유형 검사**

> 차별화된 서비스

(1) **추천 알고리즘** : 고객 맞춤형 추천 서비스
(2) **관광 테마** : 외국인 관광객들 위한 서비스로 확장한다. 제한된 시간 안에 관광 만족도를 최대로 높일 수 있는 '관광 테마'를 추천한다. 

- **향후 서비스 발전** : MBTI 검사 결과를 토대로 고객의 성격 유형과 가장 잘 맞는 관광지 테마/코스를 추천한다. 
신규 가입자 대상 MBTI 성격 유형을 검사하고, 고객이 선호하는 관광지 데이터를 학습해 

- **핵심** : 성격 유형에 근거한 관광지 선호 예측 -> 추천 시스템 구현
* Mishcel, Shoda & Smith는 2003년 논문에서 성격이 "과거 기억에 근거해 현재와 미래를 해석할 수 있는 연결고리"라 봤다. 성격이 과거 경험에 따라 결정되는데, 이에 그 사람의 경험과 성격을 분석하면 현재와 미래에 대한 개연성 있는 예측을 할 수 있다고 봤다. 

> MBTI란?

- 융(1976) 심리유형이론에 근거. 
- 외향성/직관성/감정성/인식성 이 네 개 척도를 가지고 사람의 성격을 모두 16개 유형으로 분류한다. 
(1) **외향성** : 활발한가?
(2) **직관성** : 정보를 언어와 직관 중 무엇으로 소화하나?
(3) **감정성** : 논리에 근거하나 감정에 따라 행동하나?
(4) **인식성** : 규칙을 새로 정하길 좋아하나 주어진 규칙에 순응하길 좋아하나?

- 검사 결과는 진로 및 심리 상담 등 여러 방면에 활용된다. 

> 검사 문항 구성

- 류시영, 김태희(2011)는 *외향성 지표*가 관광지 선호와 가장 밀접한 관계가 있다고 봤다. 검사의 초점은 외향성을 측정하는 데 있다.
- 검사 문항은 *20개*로 제한한다. 

> 문항 유형

- 외향성
- 직관성/감정성/인식성
- 기타
- 인구통계자료 : 나이, 혼인 여부 등

> 1. 외향성 지표
- 나는 새로운 사람 만나기를 좋아한다
- 나는 사람 돕는 것을 좋아한다
- 빠르게 대응하기보다 충분히 생각한 후 답하기를 좋아한다
- 다양한 부류의 친구들이 있다
- 쉽게 긴장을 푼다
- 나는 어울리기에 편한 사람이다. 

> 2. 직관성
- 이미 검증된 기술보다 새로운 기술 익히기를 좋아한다.
- 구체적인 것보다 비유적인 게 좋다.
- 미래보단 현재가 중요하다.
- 관광지의 설명을 듣는 것보다 사진 보는 게 더 중요하다.

> 3. 감정성/인식성문
- 나는 일을 조직하기를 즐긴다.
- 단점을 보고 비판적인 경향이 있다.
- 일을 시작하는 데서 만족을 얻는다.
- 나는 쉽게 실망한다.
- 새로운 정보를 접하면 그때마다 목표를 수정한다.
- 현재를 즐기고 일은 나중에 마무리한다.

> 4. 기타 질무
- 소셜 미디어를 자주 사용한다.
- 친구보다 가족과 더 많은 시간을 보낸다.
- 가격이 비싸도 만족도가 높으면 상관없다. 